version: '3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command:  bash -c "rm -f tmp/pids/server.pid  && ./bin/rails db:migrate && ./bin/rails s -b 0.0.0.0"
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/web
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db: {}
  web: {}